print("Welcome to the brand name generator.")
city = input("What's the name of the city you grew up in?\n")
print(city)
pet = input("What's your pet's name?\n")
print(pet)
print("Your brand name could be " + city + " " + pet)
print("Sanjay Singh")
